version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres_notes
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"  # Menggunakan port sesuai .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: openjdk:21-jdk-slim 
    build: .
    container_name: spring_notes_app
    ports:
      - "${APP_PORT}:8080"  # Menggunakan port sesuai .env
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}  # Opsi Hibernate DDL
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
